name: Output Demo

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.ver.outputs.VERSION }}

    steps:

      - id: ver

        run: |

          echo "VERSION=v1.100" >> $GITHUB_OUTPUT

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - run: echo "${{ needs.build.outputs.version }}"
